<?php
### WU GRAPHS configuration ###
// This file is generated by configurator.php

$stationName = "Sinanoba Istanbul";
$sinceY = "2016";
$sinceM = "1"; 
$sinceD = "1";
$dataSource = "wunderground";
$wdMonthLim = 12;
$wdYearLim = 12;
$wugTheme = "default";
$WUID = "ISTANBUL161";
$TZconf = "America/New_York"; 
//$fixedTime = ;
$ddFormat = 0;
$hourFormat = 0; 
$wugWidth = "640";
$wugHeight = "380";
$defaultWUGlang = "en";
$langSwitch = false;
$showSolar = true;
$wugWinW = "900";
$wugWinH = "350";
$cookieExp = 0.5;
$calcMbaroAvg = true;
$calcSolar = false;
$calcWindDir = false;
$removeSpikes = true;
$dsp = array("temp" => 10, "baro" => 1.8, "rain_rate" => 150, "rain_total" => 35, "humi" => 8);
$mysp = array("temp" => 10, "baro" => 10, "humi" => 70);
$IcacheWUfiles = false;
$WUcacheDirI = "auto";
$Iprecache = false;
$pause = 120;
$maxPre = 2;
//$refreshForced = ;
//$autoRefreshT = "";
$creditsEnabled = "false";
$creditsURL = "http://www.somesite.com";
$credits = "some site";
//$jQueryFile = "";
$loadJQuery = true;
$incTabsStyle = false;
//$testOn = ;
$updateCheck = false;
$SendName = false;
$heightCorr = "20";
$standAlone = true;
//$includeMode = ;
$spline_graphs = true;
$fopenOff = false;
//$jsPath = "";
$cookieEnabled = false;
$sendAgent = false;
$no_mb = false;
$db_i_temp = false;
$db_suv = true;
$CustomFontTheme = false;
$colorpickerFontVal = "#000000";
$CustomBgTheme = 'transparent';
$colorpickerBgVal = "#ffffff";
$baroMinMax = false;

?>